import React from 'react';
import Image from 'next/image';
import { Lines } from '@/constants';
import Link from 'next/link';


const Page: React.FC = () => {
  return (
    <div className='h-full bg-primary/30'>
      <div className='container mx-auto py-32 text-center xl:text-left flex items-center justify-center h-full'>
        {/* text */}
        <div className='flex flex-col w-full max-w-[700px]'>
          {/* text */}
          <h2 className='text-orange-400 text-center text-[55px] mb-12'>
          Chapter 3
          </h2>
          <p className="text-white">
            Hans is the first to speak out. "We should bury him." A small disagreement breaks out between Aiguo and the others. The main argument centers on whether those monstrous animals will come back. Isaac firmly insists that if the animals return, he will simply use his throwing skills on them. Now that they know how to fight the strange beasts, everything will turn out fine. Seeing that the others are against him, Aiguo concedes. The group finds a suitable place to bury Dimitri, just under the room where they first dropped down, Isaac and a few others use some large flat rocks they found around the area to dig a shallow grave. The burial process takes only thirty minutes to complete. when one digger begins to tire, someone takes their place, allowing them to complete the task quickly. After saying their goodbyes, the group looks to the jungle ahead. Once again, the discussion steers towards the question on how the group should be structured. If there should be a leader, or how decisions should be made. Aiguo and Tambwe suggest to the rest of the group, that the party tale on a more democratic form. "I believe," Tambwe explains. "That this is the best way to make use of each other's abilities, as we face unknown challenges. Isaac's pitching skills serve as a prime example of how things can turn out, if such abilities are applied correctly."
            Some of the others vocalize some hesitancey. Michael steps forward. He suggests to the others, "My people have a saying, 'democracy is two wolves and a lamb voting on what's for dinner.' I am for everyone having equal weight in what they have to say and do, but there must be restraint. Some Measure to prevent any kind of totalitarianism from arising."
            "This is not that kind of situation." Aiguo interjects. "Such measures are not necessary. Here, there can be no kind of total authority." "You are wrong, my friend!" Alejandro says, answering Aiguo's blanket declaration. "my country knows all too well how such a situation can turn tyrannical. Ever heard of Clipperton Isle?"
            Everyone shakes their heads, including Aiguo. Alejandro continues,"it was meant to be a simple colony in the 1800s. When my country entered one of its many revolutions, the colony was forgotten about. Near the end of the colonys existence, there were only a few more people on the island than what we have here. This did not stop one man from turning it into a nightmare of sexual abuse and torture for the remaining survivors.
            Ultimately they were forced to ambush and killed him to survive."
            Alejandro's example of Clipperton Isle gives the others a moment of pause. Every man stands in silence, thinking of what kind of rules will be necessary to prevent a singular authority from taking shape. Chief among all concerns in the mind of each man is the problem of the Cult of Personality. If any one individual obtains too much prestige or honor among his peers, his ability to sway them towards committing immoral acts upon others will only increase in likelihood. 
            There is no nation on Earth that hasn't fallen prey to this one simple social phenomenon. "If there can be no Leader," Manqoba asks, "What are we to make of a situation in which a decision is distasteful among the majority or minority?"
            Aiguo offers up a solution, "Perhaps the answer lies in our indeividual skillsets. In ancient China, when corruption was a its least, one's talents and skills determined where best to place them. Perhaps, relying on each other's expertise in a field of knowledge is the best course of action. As Tambwe has already suggested, but we apply it to our group structure also."
            "I think we can find some common ground there." Michael responds. "We utilize the principles of meritocracy as a guide in making decisions."
            Seeing a general sense of agreement among the others, Abrax finishes off the conversation, "I believe that relying on skills and experience will prevent unnecessary debates in the long run, save one, matters of direction and specific pathways. We may utilize experience and skill for this, but the ultimate decision must rest on a unified vote. In all other matters we can have dissent. Here, even if there is a minority, said minority must concede."
            Nods and spoken words of consent pass through the group The defeat of the second animal gives the group a sense of confidence. If it, or another shows up, they now know how to manipulate the creature's heightened sense of hearing and limited vision to their advantage. The knowledge brings comfort to the survivors, allowing them a brief respite.
            Once the main conversation dies down, and all tension from the previous encounter fades, Mosu asks the question that has been burning in everyone's mind. "What was that monster?"
            "It was a giant, furry Praying Mantis." Michael responds. "How can such a massive insect exist? Genetic Engineering?" "I don't think so." Arthur responds. "It seemed way too comfortable with the jungle. The one that ate David ran to the trees after finishing its meal. The other one retreated into the jungle for safety. I think the creature is a result of natural evolution. Simply a convergent form of two different type of classes: Mammalia and Insecta."
            Arthur picks up on the blank expressions of the others. He explains to them. "This First creature we encountered, has the size and bulk of a bear, but behaved like a Praying Mantis. Its eyesight was weak, which may explain why its hearing was precise like an Owl's. At some point in the creature's evolutionary history the function of the ear must have overtaken the animal's reliance on itss eyes. Thus, the animal's sensory organs function as we have observed."
            "And what does this have to do with convergent evolution?" Michael asks.
            "Clearly, for such a massive creature to have evolved," Arthur answer. "It needed to develop a large, stocky body, capable of handling the bulk. just like how bears possess large, stocky bodies. The bristly hair probably serbes the same function with these creatures as hair does in a bear. Heat retention and distribution, even acting as protection against water. A useful trait in the human jungle environment."
            Mosu adds. "Bats and Pteranodons are another example of CE. Both specie groups evolved membrane wings to fly. Aquatic reptiles and mammals both evolved flippers to swim in deep water. Elephants and sauropods both evolved coliumn-like feet for stability. Adaptations necessary for the niches they filled in."
            Arthur nods, explaining further, "While we cannot account for all possibilities, I believe that if we use this as a basis for our movements through the jungle our chances for survival will increase. We can use our knowledge of animals on Earth and compare their adaptations to animals we might encouter here. Giving us an idea on how to proceed. Those among us with living experience of these types of environments should be the ones who guide us. They're the most likely to see signs of an animal in advance."
            Everyone agrees with Arthur's assessment. After a few minutes of deliberation, Akol, Moussa, Isaac, Ye-Jun, Sang, Paulo, Isaiah, Elias, and Tambwe are elected to lead the group. As these nine have the most experienvce, growing up in similar environments. The men agree that the nine selected are the group's best chance at navigating the unknown. All nine men take up leading positions in the form of an inverted crescent moon, while the others stick closely behind them.
            Franco is the only one to refrain from actively participating with the rest of the survivors. During much of their deliberations, the young Chilean sat on the ground with his head between his legs. That massive monster and David's horrible death left him frozen with fear. It seems best to him to simply lay down and do nothing.
            Michael kneels down next to Franco to talk. "What's wrong?"
            "I don't know that I can do this."Franco responds. "That was just the first encounter. How much worse is it going to get?"
            Franco's mentality is understandabble to Michael. The young man has seen something truly terrifying. Something only ever speculated avout in the realms of fantasy and science fiction, and yet here and now it is their reality. Michael knows that he needs to raise Franco's morale. It is a concept well understood in business, Low morale leads to complacent employees, and complacent employees leads to low output and retention of employees. As a manager, Michael had to learn how to motivate people and raise morale.
            "I get it. We're all scared of ending up like David." Michael says. "But look at it this way. If you do nothing, you will die. Our only hope for surviving is by moving forward Besides, we don't know if there are other animals like that or not. Maybe that creature was the worst hurdle. We cannot know. We can only fight to survive, and the first step for surviving is moving forward."
            The words spoken by Michael seem to do the trick. Franco looks up at the young American with tears in his eyes and nods. Michael helps him up onto his feet. The rest of the group give Michael an approving nod for his efforts, then turn their focus back to the forest ahead of them. Now that everyone is ready, they begin to move on. The brightly lit sky quickly changes under the dense foliage of the rainforest. In the low-light conditions brought about by the thick canopy above them, simple roots and branches become serious tripping hazards. The party leaders, to the relief of the others, do not suffer from the same issue. Their peoples are well adapted to such conditions, retaining a strong night-vision. An occasional break in the upper canopy provides some light, allowing the others to better perceive their environment, and giving the leaders an opportunity to relax from being hypervigilant.
            Ten minutes pass by as the group moves into the thick of the rainforest. Insects can be heard buzzing about and giving off a cacophony of different sounds. In their march, they come across several odd-looking insect species that likely fill in the lower levels of a jungle ecology. Ranging from, small furry ant-like animals, to scaly otter-like creatures the size of small dogs. None of these freakish looking animals seem particularly interested in the visitors. For the humans, each new encounter with one of these strange animals acts as a reminder that they are in an alien environment.
            A strange and sudden cry pierces through the cadence of the rainforest. The survivors to look anxiously around for the source. When another cry echoes more clearly above their heads, the group looks up into the canopy. High up in the trees they spy out an animal straight out of human mythology, sitting calmly on a large branch.
            The creature's wings extend out from its forearms. They are made of membrane like that of a bat while the body itself is covered head to tail in brightly glistening scales. Its head is the most distinguished of all the features the animal presents. The snout is pointed, and two horns extend out from the back of its head by about five inches. Its eyes have vertical pupils, green in color. The back, head, and outer hind legs are a dark shade of green, with dark brown spots running in sequence from the neck, all the way down to the tail. Its underside is a uniform light green.
            "Is that what I think it is?" Arthur asks, a boyhood-like wonder upon his face. Michael answer, "It definitely looks like one."
            "They cannot be real." Aiguo says. His face, like Arthur's, full of wonder and surprise.
            Sang, Sean, and Hans, Jesse, Mosu, Ye-Jun and Tarkhan all join in, gazing upon the creature in wonder and amazement. The rest all stare at each other with bewilderment, unsure why their counterparts seem so fixated on the animal. Mosu notices his fellow survivors' confusion and explains to them.
            "The animal looks like a dragon." He tells them. "This one has the appearance of a western style dragon. More familiar within Western folklore than the snake-like dragons found in many Asian cultures. It seems too good to be true."
            Sean speaks his mind, "Sadly, you are correct. This is probably just a flying reptile. Something like our Pteranodons. This one, must have simply evolved along similar lines"
            "Its head looks almost like a Monitor Lizard. Isaac comments. "Only, more dragon-like."
            Arthur's eyes light up. "I think you are correct, Isaac. Maybe this creature evolved from a reptilian-like species. Something similar to the monitor lizards we see on Earth."
            The group watches the creature stretch out its wings, then jump off the branch it is perched on. Once the air catches under the animal's wings, it flies off, occasionally flapping to regain lost height. Any further observation of the animal is cut short by its exit, The group remains for some time, gazing fondly up the section of the canopy where the creature disappeared to. Akol finally breaks the collective silence, "We should Keep moving. This animal has left us alone, but we cannot guarantee that the next wonder we behold won't be an animal of equal or greater danger than that bear-mantis."
            Just the mention of the bear-mantis snaps everyone back to their present situation. The group begins to move onward again through the rainforest. The landscape undergoes a radical change further in. A far more drastic transformation than anything the men could have expected. Tree roots rise out of the ground, changing from the normal cylindrical digger roots of all known trees into large vascular walls. Walls whose height eventually eclipse the tallest members of the group. Moving further into this section of the forest brings with it an unearthly darkness. The Further into the maze they walk, the darker it becomes. Barely ten minutes in, and the world around them is like the twilight of evening.
            The vascular walls are not uniform in direction, randomly intersecting with one another. It comes to resemble something like a maze in the minds of the men. An idea that is further complicated by the fact the walls do not run in any direction with consistency. Sporting curves and odd angles without regard to the inconvenience they cause the survivors. Mosu coins the term "root-maze" to describe their predicament. A sentiment that is not viewed fondly of by the others. 
            In the darkness, a transformation takes place within the minds of the group. Paranoia starts to consume them, putting the men into a state of hypervigilance. Every chirp from the unseen canopy above them, or the skittering of an unknown creature high upon the walls provokes an intense pause. Whereby the men spend several minutes intensley focusing on the direction of the sound's origin. Thoughts of some imaginary monster lying in wait, ready to ambush them pervade their minds. In this alien and unforgiving jungle, none believe that such an encounter is unlikely. Aiguo is near the front with the leaders. He looks back to see that some of the other survivors are lagging behind. Mosu and Franco in particular. Tambwe, Michael, Alejandro, and a few others do their best. All of their effort seems like a waste to Aiguo. In his mind, it is best to cut them loose and leave them behind. Such weak individuals will onlu be a liabilitu to the others. Increase their risk of failure.
            The men push themselves to continue through the maze, regardless of whatever hidden dangers they might have to face. In the pitch blackness, the men remain ever watchful of their front and back, and above their heads. Despite the group's fears and anxieties, no new horror manifests itself. For the entire 45-minute walk through the claustrophobic root-maze, they remain unmolested. The occasional cadence of unseen insects, and the cry of the tiny dragons provide some comfort. Even though the men can't see them.
            Inside the tight walkways of the root maze, a thirst for water grows within the survivors. The oppressive heat and humid air leave the men soaking in their own sweat. Every breath becomes a difficult labor in and of itself. A few of them instinctively reach for a water bottle or canteen in order to rehydrate, only to find nothing at their waists. They must find water soon or they will be at risk of succumbing to dehydration. Despite the absurdity of dying by dehydration in a rainforest, as some might think, these occurrences can and do happen. Rainforests can be extremely hot during the daytime but are equally known fortheir high levels of humidity. Even in an environment with high humidity, a single person will still sweat quite profusely. An act that drains a person's internal water reservoir. The densely humid atmosphere makes int difficult for wet objects to dry, preventing the sweat from evaporating and cooling a person. Perspiration is one of the leading causes of dehydration resulting in death. Overheating is the other.
            Due to these reasons, access to water is an essential part of survival in every rainforest environment on Earth. If a person sweats too much, they risk falling into a state of dehydration, which would result in death if water lost is not replaced. This is the problem they face now. The group will need to find water quickly. If there is no water is available immediately after the root-maze, then they will find themselves in danger of failing the Crucible after only the second major hurdle.
            While these thoughts weigh on the mind, those in the front notice a change in the atmosphere. the air slowly becomes less oppressive on the lungs and body, and the area above them is becoming lighter. Some of them can even make out the upper canopy, if only barely. Hope springs up within the group. They hurry alonf their current path, almost recklessly, just to get back out into the open.          
          </p>
        </div>
      </div>

    </div>
  );
};

export default Page;